[package]
name = "casm"
version = "0.1.0"
authors = ["Will Hawkins <hawkinsw@obs.cr>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [ "libcasm" ]

[dependencies]
libcasm = { path = "libcasm" }
