---
name: x86_64
memory_widths: [8, 16, 32, 64, 128]
user_registers:
  - canonical_name: rax
    subregisters:
      - width: 8
        name: al
      - width: 16
        name: ax
      - width: 32
        name: eax
      - width: 64
        name: rax
  - canonical_name: rbx
    subregisters:
      - width: 8
        name: bl
      - width: 16
        name: bx
      - width: 32
        name: ebx
      - width: 64
        name: rbx
  - canonical_name: rcx
    subregisters:
      - width: 8
        name: cl
      - width: 16
        name: cx
      - width: 32
        name: ecx
      - width: 64
        name: rcx
