[package]
name = "libcasm"
version = "0.1.0"
authors = ["Will Hawkins <hawkinsw@obs.cr>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.197", features = [ "derive" ]}
serde_yaml = "0.9.34"
